name: Rotate Rad Every 10 Minutes
on:
  schedule:
  - cron: "5-59/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Rotate Rad
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Pillow
      run: python -m pip install Pillow

    - name: Run Python Script
      run: python main.py

    - name: Commit files if changed
      run: |
        git config --local user.email "somemail@domain.com"
        git config --local user.name "github-actions[bot]"
        git update-index -q --refresh
        git diff-index --quiet HEAD -- || git commit -m "[Generate]" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main